### ISSUE TITLE
CP overview widgets

### ISSUE THREAD

**Issue by SETU-WEB** [reusserdesign/RD-Control-Panel-Tweaks#1]
Hi , the button color changes doesn't seem to apply for the buttons on the members , channels , content and rss widgets on the default control panel

**Comment by JasonBoothman** [comment]
Thanks for bringing this to my attention @WITwebmaster . I'll take a look at this and try to get it taken care of within the next day or two.

**Comment by JasonBoothman** [comment]
@WITwebmaster - 

The default ExpressionEngine action button styling has been fixed is the 1.01. release. This should handle what you were seeing on the Members & Channels pages. As for Content and RSS Widgets - they are displaying correct for me so I think it's probably a CSS caching issue. Make sure after changing anything in the add-on you clear the cached CSS in your browser so the changes reflect correctly everywhere.

Let me know if this takes care of your issue!

**Comment by SETU-WEB** [comment]
Hi @jasonboothman 
tested the new update and its all working as expected. Great plugin , its great to be able to customize the control panel.
@WITwebmaster

**Comment by JasonBoothman** [comment]
Awesome! Glad to hear you like it!
