### ISSUE TITLE
Image button style override doesn't apply to new image drag and drop fields 

### ISSUE THREAD

**Issue by SETU-WEB** [reusserdesign/RD-Control-Panel-Tweaks#3]
Expressionengine 5.1.0 added support for drag and drop uploading, the buttons color style override doesn't apply to this element 
![Uploading upload.png…]()

**Comment by JasonBoothman** [comment]
Thank you for bringing this to my attention. I'll work on taking a look at it and getting a fix published.

**Comment by JasonBoothman** [comment]
This has been fixed in the latest version I just pushed up - [1.1.1](https://github.com/reusserdesign/RD-Control-Panel-Tweaks/tree/1.1.1). You may need to clear your cache to see the CSS changes after updating.
